# Generated by Django 4.1.3 on 2024-02-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='face',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='header',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legs',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='male',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='torso',
        ),
    ]
