# Generated by Django 4.1.3 on 2024-05-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_age_remove_customuser_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
