# Generated by Django 4.1.3 on 2024-05-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_task_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
