# Generated by Django 4.1.3 on 2024-05-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_taskresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskResponse',
        ),
    ]
