# Generated by Django 4.1.3 on 2024-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_rating_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(choices=[('/static/hero1.png', 'Hero 1'), ('/static/hero2.png', 'Hero 2'), ('/static/hero3.png', 'Hero 3')], default='hero1', max_length=100),
        ),
    ]
