# Generated by Django 4.1.3 on 2024-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
