# Generated by Django 4.1.3 on 2024-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(choices=[('hero1.png', 'Hero 1'), ('hero2.png', 'Hero 2'), ('hero3.png', 'Hero 3')], default='/static/hero1.png', max_length=100),
        ),
    ]
